# coding: utf-8
class AddDataPeople < ActiveRecord::Migration
  def up
    #Localidad.create :name => '16 DE JULIO' ,:departamento_id=> 1
Person.create :id =>		1	,:name => 'Acha '
Person.create :id =>		2	,:name=>	'Acha, Daniela'
Person.create :id =>		3	,:name=>	'Acosta, Norma'
Person.create :id =>		4	,:name=>	'Aguirre, Esther'
Person.create :id =>		5	,:name=>	'Aguirre, Irma'
Person.create :id =>		6	,:name=>	'Aguirre, Norma'
Person.create :id =>		7	,:name=>	'Alarcón '
Person.create :id =>		8	,:name=>	'Albarengue, Claudia'
Person.create :id =>		9	,:name=>	'Alvarez, Mariela'
Person.create :id =>		10	,:name=>	'Andino, Lucas'
Person.create :id =>		11	,:name=>	'André '
Person.create :id =>		12	,:name=>	'André, Omar'
Person.create :id =>		13	,:name=>	'Asan, Raquel'
Person.create :id =>		14	,:name=>	'Ayala '
Person.create :id =>		15	,:name=>	'Azuaga, Fabián'
Person.create :id =>		16	,:name=>	'Azuaga, José'
Person.create :id =>		17	,:name=>	'Banegas '
Person.create :id =>		18	,:name=>	'Barriera, Laura Beatriz'
Person.create :id =>		19	,:name=>	'Barriera, Sergio'
Person.create :id =>		20	,:name=>	'Barrios, Elvira'
Person.create :id =>		21	,:name=>	'Barrios, Griselda'
Person.create :id =>		22	,:name=>	'Battistella, Nicolás'
Person.create :id =>		23	,:name=>	'Benitez '
Person.create :id =>		24	,:name=>	'Benitez '
Person.create :id =>		25	,:name=>	'Benitez, Claudio'
Person.create :id =>		26	,:name=>	'Benitez, Silvia'
Person.create :id =>		27	,:name=>	'Bertuni '
Person.create :id =>		28	,:name=>	'Bogado '
Person.create :id =>		29	,:name=>	'Bogarín, Carolina'
Person.create :id =>		30	,:name=>	'Brouet, Aldo'
Person.create :id =>		31	,:name=>	'Brugiati Guntren '
Person.create :id =>		32	,:name=>	'Budniewski '
Person.create :id =>		33	,:name=>	'Bugliolo, Lucas'
Person.create :id =>		34	,:name=>	'Cabal '
Person.create :id =>		35	,:name=>	'Cabal, Eduardo'
Person.create :id =>		36	,:name=>	'Cabañas, Teresa'
Person.create :id =>		37	,:name=>	'Canalis '
Person.create :id =>		38	,:name=>	'Cano, Delicias'
Person.create :id =>		39	,:name=>	'Caporizzo, Alicia'
Person.create :id =>		40	,:name=>	'Carello, Natalia'
Person.create :id =>		41	,:name=>	'Carnevalle, Jorge'
Person.create :id =>		42	,:name=>	'Carrizo, Adrián'
Person.create :id =>		43	,:name=>	'Carrizo, Miguel'
Person.create :id =>		44	,:name=>	'Carrizo, Vanesa'
Person.create :id =>		45	,:name=>	'Casa, Susana'
Person.create :id =>		46	,:name=>	'Castro, Jorge Omar'
Person.create :id =>		47	,:name=>	'Catorano '
Person.create :id =>		48	,:name=>	'Ceballos, Feliza'
Person.create :id =>		49	,:name=>	'Centurión, Nélida'
Person.create :id =>		50	,:name=>	'Ceparo '
Person.create :id =>		51	,:name=>	'Ceparo, Ezequiel'
Person.create :id =>		52	,:name=>	'Chacon, Pablo'
Person.create :id =>		53	,:name=>	'Chapuy '
Person.create :id =>		54	,:name=>	'Chavez '
Person.create :id =>		55	,:name=>	'Chia, Pablo'
Person.create :id =>		56	,:name=>	'Chumilla, Horacio'
Person.create :id =>		57	,:name=>	'Clemente '
Person.create :id =>		58	,:name=>	'Colli, Jeorgina'
Person.create :id =>		59	,:name=>	'Contreras, Hugo'
Person.create :id =>		60	,:name=>	'Corti '
Person.create :id =>		61	,:name=>	'0'
Person.create :id =>		62	,:name=>	'Di Pietro, Carina'
Person.create :id =>		63	,:name=>	'Diaz, Ángela'
Person.create :id =>		64	,:name=>	'Diaz, Rosana'
Person.create :id =>		65	,:name=>	'Dobler, Adrián'
Person.create :id =>		66	,:name=>	'Duarte'
Person.create :id =>		67	,:name=>	'Espinosa'
Person.create :id =>		68	,:name=>	'0'
Person.create :id =>		69	,:name=>	'Esquivel '
Person.create :id =>		70	,:name=>	'Esquivel, Luciana'
Person.create :id =>		71	,:name=>	'Eusebi, Julio'
Person.create :id =>		72	,:name=>	'Fanchini, Sergio'
Person.create :id =>		73	,:name=>	'Faría, Fabiana'
Person.create :id =>		74	,:name=>	'Faure, Cristina'
Person.create :id =>		75	,:name=>	'Ferreyra, Eduardo'
Person.create :id =>		76	,:name=>	'Ferreyra, Fermino'
Person.create :id =>		77	,:name=>	'Ferreyra, Juan'
Person.create :id =>		78	,:name=>	'Fijman '
Person.create :id =>		79	,:name=>	'Fonseca, David'
Person.create :id =>		80	,:name=>	'Forzano '
Person.create :id =>		81	,:name=>	'Frutos '
Person.create :id =>		82	,:name=>	'Fuga, Marcelo'
Person.create :id =>		83	,:name=>	'Galarza, Rosa'
Person.create :id =>		84	,:name=>	'0'
Person.create :id =>		85	,:name=>	'Galmes, Pedro'
Person.create :id =>		86	,:name=>	'Galván, Diego'
Person.create :id =>		87	,:name=>	'García, José'
Person.create :id =>		88	,:name=>	'Geri '
Person.create :id =>		89	,:name=>	'Gimenez '
Person.create :id =>		90	,:name=>	'Gimenez, Vanina'
Person.create :id =>		91	,:name=>	'Gingene '
Person.create :id =>		92	,:name=>	'Gomez '
Person.create :id =>		93	,:name=>	'Gomez, Amelia'
Person.create :id =>		94	,:name=>	'Gómez, María Elena'
Person.create :id =>		95	,:name=>	'Gomez, Miguel'
Person.create :id =>		96	,:name=>	'Gómez, Sergio'
Person.create :id =>		97	,:name=>	'Gonzalez, Nadia'
Person.create :id =>		98	,:name=>	'Gorriti, Germán'
Person.create :id =>		99	,:name=>	'Grosso, Rodolfo'
Person.create :id =>		100	,:name=>	'Gryciuk, Emiliano'
Person.create :id =>		101	,:name=>	'Guarino, Juan'
Person.create :id =>		102	,:name=>	'Guerrero, Liliana'
Person.create :id =>		103	,:name=>	'Guevara '
Person.create :id =>		104	,:name=>	'Gutierrez, Graciela'
Person.create :id =>		105	,:name=>	'Hernández, Carmen de'
Person.create :id =>		106	,:name=>	'Hernandez, Mónica'
Person.create :id =>		107	,:name=>	'Hoffmann '
Person.create :id =>		108	,:name=>	'Honnorat '
Person.create :id =>		109	,:name=>	'Iancovich, Sara'
Person.create :id =>		110	,:name=>	'Ibarra, Sonia'
Person.create :id =>		111	,:name=>	'Ifran, Mario'
Person.create :id =>		112	,:name=>	'Iglesias, Francisco'
Person.create :id =>		113	,:name=>	'Juncos '
Person.create :id =>		114	,:name=>	'Lauría '
Person.create :id =>		115	,:name=>	'Ledesma '
Person.create :id =>		116	,:name=>	'Leyes, Gladis'
Person.create :id =>		117	,:name=>	'Linares, Sergio'
Person.create :id =>		118	,:name=>	'Llano, José'
Person.create :id =>		119	,:name=>	'Lucero, Ramón'
Person.create :id =>		120	,:name=>	'Maidana'
Person.create :id =>		121	,:name=>	'Maidana, Margarita'
Person.create :id =>		122	,:name=>	'Maldonado, Andrea'
Person.create :id =>		123	,:name=>	'Manchula, Silvia'
Person.create :id =>		124	,:name=>	'Mandirola, Victor'
Person.create :id =>		125	,:name=>	'Manjka,Ricardo'
Person.create :id =>		126	,:name=>	'Mansilla, Cristian'
Person.create :id =>		127	,:name=>	'Marquez, Jorge'
Person.create :id =>		128	,:name=>	'Martinez '
Person.create :id =>		129	,:name=>	'Martinez '
Person.create :id =>		130	,:name=>	'Martinez, Carlos'
Person.create :id =>		131	,:name=>	'Martinez, Lorena'
Person.create :id =>		132	,:name=>	'Medina, Ivana'
Person.create :id =>		133	,:name=>	'Medina, Jorge'
Person.create :id =>		134	,:name=>	'Meier, Marcelo'
Person.create :id =>		135	,:name=>	'Mendez, Raúl'
Person.create :id =>		136	,:name=>	'Mesa '
Person.create :id =>		137	,:name=>	'Monticolo, Pablo'
Person.create :id =>		138	,:name=>	'0'
Person.create :id =>		139	,:name=>	'Morel, Alberto'
Person.create :id =>		140	,:name=>	'Morelli '
Person.create :id =>		141	,:name=>	'Muraca, Adelmo'
Person.create :id =>		142	,:name=>	'Ocampo, Hugo'
Person.create :id =>		143	,:name=>	'Ojeda '
Person.create :id =>		144	,:name=>	'Oleinik, Maximiliano'
Person.create :id =>		145	,:name=>	'Olivera, Ernesto'
Person.create :id =>		146	,:name=>	'Ordoñez, Natalia'
Person.create :id =>		147	,:name=>	'Otamendi, Marcos'
Person.create :id =>		148	,:name=>	'Otamendi, Osvaldo'
Person.create :id =>		149	,:name=>	'Otamendi, Sebastián'
Person.create :id =>		150	,:name=>	'Padilla, José'
Person.create :id =>		151	,:name=>	'Pagani, Gloria'
Person.create :id =>		152	,:name=>	'Palavecino '
Person.create :id =>		153	,:name=>	'Paredes '
Person.create :id =>		154	,:name=>	'Paredes, Eduardo'
Person.create :id =>		155	,:name=>	'Paz '
Person.create :id =>		156	,:name=>	'Pereyra, Sergio'
Person.create :id =>		157	,:name=>	'Perez, Marianela'
Person.create :id =>		158	,:name=>	'Perez, Ricardo'
Person.create :id =>		159	,:name=>	'0'
Person.create :id =>		160	,:name=>	'Perez, Roberto'
Person.create :id =>		161	,:name=>	'Petiton, Ana María'
Person.create :id =>		162	,:name=>	'Pintos, Pablo'
Person.create :id =>		163	,:name=>	'Pintos, Viviana'
Person.create :id =>		164	,:name=>	'Pizarro, Héctor'
Person.create :id =>		165	,:name=>	'Placeres, Irma'
Person.create :id =>		166	,:name=>	'0'
Person.create :id =>		167	,:name=>	'0'
Person.create :id =>		168	,:name=>	'Pogonza, Norma'
Person.create :id =>		169	,:name=>	'Pozzo, Laura'
Person.create :id =>		170	,:name=>	'Querini, Alberto'
Person.create :id =>		171	,:name=>	'Quiroz, Raquel'
Person.create :id =>		172	,:name=>	'Ramirez, José Luis'
Person.create :id =>		173	,:name=>	'Ramirez, Lidia'
Person.create :id =>		174	,:name=>	'Ramirez, María de los Ángeles'
Person.create :id =>		175	,:name=>	'Ramirez, Plácido'
Person.create :id =>		176	,:name=>	'Ramirez, Vanesa'
Person.create :id =>		177	,:name=>	'Rastellini '
Person.create :id =>		178	,:name=>	'Recanatini '
Person.create :id =>		179	,:name=>	'Recce, Rosa'
Person.create :id =>		180	,:name=>	'Rios, Manuel'
Person.create :id =>		181	,:name=>	'Rivero, Susana'
Person.create :id =>		182	,:name=>	'Roble '
Person.create :id =>		183	,:name=>	'Roca, María Elena'
Person.create :id =>		184	,:name=>	'Rodriguez, Carlos'
Person.create :id =>		185	,:name=>	'Rodriguez, Faustino'
Person.create :id =>		186	,:name=>	'Roman '
Person.create :id =>		187	,:name=>	'Romero, Sonia Lorena'
Person.create :id =>		188	,:name=>	'Rotela '
Person.create :id =>		189	,:name=>	'Ruggenini, Marcelo'
Person.create :id =>		190	,:name=>	'Ruiz '
Person.create :id =>		191	,:name=>	'Ruiz '
Person.create :id =>		192	,:name=>	'Ruiz, Juan'
Person.create :id =>		193	,:name=>	'Salas '
Person.create :id =>		194	,:name=>	'Salinas, Herminda'
Person.create :id =>		195	,:name=>	'Sanchez'
Person.create :id =>		196	,:name=>	'Sanchez, Diego'
Person.create :id =>		197	,:name=>	'Sanchez, María'
Person.create :id =>		198	,:name=>	'Santa Cruz, Rosana'
Person.create :id =>		199	,:name=>	'Sequeira, Estela'
Person.create :id =>		200	,:name=>	'Sesma, Ariel'
Person.create :id =>		201	,:name=>	'Soria, Ester'
Person.create :id =>		202	,:name=>	'Sosa, Federico'
Person.create :id =>		203	,:name=>	'Soto, Ana'
Person.create :id =>		204	,:name=>	'Strina '
Person.create :id =>		205	,:name=>	'Suarez '
Person.create :id =>		206	,:name=>	'Taborda, Cristian'
Person.create :id =>		207	,:name=>	'Taborda, Nelson'
Person.create :id =>		208	,:name=>	'Tavella, Huberto'
Person.create :id =>		209	,:name=>	'Tenaglia '
Person.create :id =>		210	,:name=>	'Torres, Daniel'
Person.create :id =>		211	,:name=>	'Torres, Iván Abel'
Person.create :id =>		212	,:name=>	'Trevisan, Raquel'
Person.create :id =>		213	,:name=>	'Trifilio, Fernando'
Person.create :id =>		214	,:name=>	'Vallejos, Sergio'
Person.create :id =>		215	,:name=>	'Vasilosuki, Andrea'
Person.create :id =>		216	,:name=>	'Vazquez '
Person.create :id =>		217	,:name=>	'Vidaechea, Juan'
Person.create :id =>		218	,:name=>	'Viña '
Person.create :id =>		219	,:name=>	'Yódice '
Person.create :id =>		220	,:name=>	'Zabala, Daniel'
Person.create :id =>		221	,:name=>	'Zalazar, Carlos'
Person.create :id =>		222	,:name=>	'Zapata, Gonzalo'
Person.create :id =>		223	,:name=>	'Zeballos, Marta'
Person.create :id =>		284	,:name=>	' Martinez-'
Person.create :id =>		290	,:name=>	' Rios-'
Person.create :id =>		294	,:name=>	' Viñaveya-'
Person.create :id =>		297	,:name=>	' Gimenez-'
Person.create :id =>		300	,:name=>	' Diaz-'
Person.create :id =>		306	,:name=>	' Argüello-'
Person.create :id =>		307	,:name=>	' Ballari-'
Person.create :id =>		310	,:name=>	' Segovia-'
Person.create :id =>		311	,:name=>	' Planells-'
Person.create :id =>		314	,:name=>	' Zursmitten-'
Person.create :id =>		315	,:name=>	' Marelli-'
Person.create :id =>		317	,:name=>	' Fussi-'
Person.create :id =>		320	,:name=>	' Vanni-'
Person.create :id =>		330	,:name=>	' Pogliani-'
Person.create :id =>		333	,:name=>	' Mondoni-'
Person.create :id =>		336	,:name=>	' Cabaña-'
Person.create :id =>		337	,:name=>	' Bernusi-'
Person.create :id =>		340	,:name=>	' Escobar-'
Person.create :id =>		343	,:name=>	' Bastián-'
Person.create :id =>		352	,:name=>	' Romeo-'
Person.create :id =>		361	,:name=>	' Lucero-'
Person.create :id =>		363	,:name=>	' Carpio-'
Person.create :id =>		364	,:name=>	' Vassel-'
Person.create :id =>		371	,:name=>	' Lezcano-'
Person.create :id =>		372	,:name=>	' Centurión-'
Person.create :id =>		374	,:name=>	' Romero-'
Person.create :id =>		375	,:name=>	' Arteaga-'
Person.create :id =>		386	,:name=>	' Hidalgo-'
Person.create :id =>		390	,:name=>	' Lovera-'
Person.create :id =>		391	,:name=>	' Escobar-'
Person.create :id =>		396	,:name=>	' Gigena-'
Person.create :id =>		397	,:name=>	' Cabaña-'
Person.create :id =>		398	,:name=>	' Sarmiento-'
Person.create :id =>		411	,:name=>	' Diaz-'
Person.create :id =>		412	,:name=>	' Lopez-'
Person.create :id =>		419	,:name=>	' García-'
Person.create :id =>		423	,:name=>	' Floridi-'
Person.create :id =>		426	,:name=>	' Frutos-'
Person.create :id =>		435	,:name=>	' Ruiz-'
Person.create :id =>		436	,:name=>	' Ruiz-'
Person.create :id =>		438	,:name=>	' Medina-'
Person.create :id =>		460	,:name=>	' Vega-'
Person.create :id =>		461	,:name=>	' Cantard-'
Person.create :id =>		465	,:name=>	' Héctor-'
Person.create :id =>		469	,:name=>	' Sellos-'
Person.create :id =>		471	,:name=>	' Lucero-'
Person.create :id =>		473	,:name=>	' Palavecino-'
Person.create :id =>		474	,:name=>	' Zampar-'
Person.create :id =>		476	,:name=>	' Morel-'
Person.create :id =>		487	,:name=>	' Serra-'
Person.create :id =>		488	,:name=>	' Noriega-'
Person.create :id =>		492	,:name=>	' Beltrocco-'
Person.create :id =>		499	,:name=>	' Fructuoso-'
Person.create :id =>		501	,:name=>	' Duquez-'
Person.create :id =>		502	,:name=>	' Nasso-'


  end

  def down
  end
end
